[package]
name = "aoc01"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.29"
reqwest = "0.11.22"
tokio = { version = "1.34.0", features = ["full"] }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
